using E_Commerce_App.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace E_Commerce_App.Data.Seeds
{
    public class ProductSeed : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> builder)
        {
            List<Product> products = new List<Product>
            {
                new Product(){Id="1", Name="Xiaomi Redmi Note 10", CreationDate=DateTime.Now,
                    Description="Xiaomi Redmi Note 10", Price=4000, Discount=5,
                    Url="xiaomi-redmi-note10", IsHome=true, MainImage="xiaomi-redmi-note10.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="2", Name="Iphone 12 | Apple", CreationDate=DateTime.Now,
                    Description="Iphone 12 | Apple", Price=12000, Discount=2,
                    Url="iphone12-apple", IsHome=true, MainImage="iphone12.png",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="3", Name="Iphone 11 | Apple", CreationDate=DateTime.Now,
                    Description="Iphone 11 | Apple", Price=10000,
                    Url="iphone11-apple", IsHome=true, MainImage="iphone11.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="4", Name="Iphone SE2 | Apple", CreationDate=DateTime.Now,
                    Description="Iphone SE2 | Apple", Price=8500,
                    Url="iphonese2-apple", IsHome=true, MainImage="iphonese.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="5", Name="Iphone 8 Plus | Apple", CreationDate=DateTime.Now,
                    Description="Iphone 8 Plus | Apple", Price=6758,
                    Url="iphone8plus-apple", IsHome=true, MainImage="iphone8plus.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="6", Name="Iphone 8 | Apple", CreationDate=DateTime.Now,
                    Description="Iphone 8 | Apple", Price=5800, Discount=3,
                    Url="iphone8-apple", IsHome=true, MainImage="iphone8.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="7", Name="Samsung Galaxy S21", CreationDate=DateTime.Now,
                    Description="Samsung Galaxy S21", Price=9000, Discount=5,
                    Url="samsung-galaxy-s21", IsHome=true, MainImage="samsung-galaxy-s21.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="8", Name="Samsung Galaxy S10", CreationDate=DateTime.Now,
                    Description="Samsung Galaxy S10", Price=6000, Discount=10,
                    Url="samsung-galaxy-s10", IsHome=true, MainImage="samsung-galaxy-s10.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="9", Name="Samsung Galaxy M20", CreationDate=DateTime.Now,
                    Description="Samsung Galaxy M20", Price=4000, Discount=15,
                    Url="samsung-galaxy-m20", IsHome=true, MainImage="samsung-galaxy-m20.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="10", Name="Samsung Galaxy A50", CreationDate=DateTime.Now,
                    Description="Samsung Galaxy A50", Price=4500,
                    Url="samsung-galaxy-a50", IsHome=true, MainImage="samsung-galaxy-a50.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="11", Name="Xiaomi Redmi Note 8", CreationDate=DateTime.Now,
                    Description="Xiaomi Redmi Note 8", Price=2600, Discount=5,
                    Url="xiaomi-redmi-note8", IsHome=true, MainImage="xiaomi-redmi-note8.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="12", Name="Macbook Pro M1 | Apple", CreationDate=DateTime.Now,
                    Description="Macbook Pro M1 | Apple", Price=16000,
                    Url="macbook-pro-m1", IsHome=true, MainImage="macbook-pro-m1.jfif",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="13", Name="Macbook Pro 19 | Apple", CreationDate=DateTime.Now,
                    Description="Macbook Pro 19 | Apple", Price=21000,
                    Url="macbook-pro-19", IsHome=true, MainImage="macbook-pro-19.jfif",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="14", Name="Macbook Air | Apple", CreationDate=DateTime.Now,
                    Description="Macbook Air || Apple", Price=14000,
                    Url="macbook-air", IsHome=true, MainImage="macbook-air.jfif",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="15", Name="Huawei P9 Lite 2017", CreationDate=DateTime.Now,
                    Description="Huawei P9 Lite 2017", Price=1850, Discount=2,
                    Url="huawei-p9-lite-2017", IsHome=true, MainImage="huawei-p9-lite-2017.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="16", Name="Monster Notebook", CreationDate=DateTime.Now,
                    Description="Monster Game Notebook", Price=8560, Discount=5,
                    Url="monster-notebook", IsHome=true, MainImage="monster-notebook.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="17", Name="Dell Laptop Pc", CreationDate=DateTime.Now,
                    Description="Dell Laptop Pc İş İstasyonu", Price=14500, Discount=8,
                    Url="dell-is-istasyonu", IsHome=true, MainImage="dell-is-istasyonu.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="18", Name="Asus Zenbook Laptop", CreationDate=DateTime.Now,
                    Description="Asus Zenbook Laptop Pc", Price=12000, Discount=1,
                    Url="asus-zenbook", IsHome=true, MainImage="asus-zenbook.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="19", Name="Arçelik Buzdolabı", CreationDate=DateTime.Now,
                    Description="Arçelik Buzdolabı", Price=4600, Discount=5,
                    Url="arcelik-buzdolabi", IsHome=true, MainImage="arcelik-buzdolabi.png",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="20", Name="Bosch Çamaşır Makinesi", CreationDate=DateTime.Now,
                    Description="Bosch Çamaşır Makinesi", Price=3528,
                    Url="bosch-camasir-makinesi", IsHome=true, MainImage="bosch-camasir-makinesi.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="21", Name="Canon EOS 750D", CreationDate=DateTime.Now,
                    Description="Canon EOS 750D", Price=6540,
                    Url="canon-eos750d", IsHome=true, MainImage="canon-eos750d.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="22", Name="Nikon D5600", CreationDate=DateTime.Now,
                    Description="Nikon D5600", Price=5980, Discount=5,
                    Url="nikon-d5600", IsHome=true, MainImage="nikon-d5600.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="23", Name="LG Nanocell Tv", CreationDate=DateTime.Now,
                    Description="LG Nanocell Tv", Price=11000, Discount=10,
                    Url="lg-nanocell-tv", IsHome=true, MainImage="lg-nanocell-tv.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="24", Name="Samsung 4K Curved Tv", CreationDate=DateTime.Now,
                    Description="Samsung 4K Curved Tv", Price=12000, Discount=9,
                    Url="samsung-curved-tv", IsHome=true, MainImage="samsung-curved-tv.png",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="25", Name="Apple Watch SE", CreationDate=DateTime.Now,
                    Description="Apple Watch SE", Price=2550,
                    Url="apple-watch-se", IsHome=true, MainImage="apple-watch-se.png",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="26", Name="Xiaomi Mi Band", CreationDate=DateTime.Now,
                    Description="Xiaomi Mi Band", Price=600, Discount=12,
                    Url="xioami-mi-band", IsHome=true, MainImage="xioami-mi-band.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="27", Name="Mouse Razer", CreationDate=DateTime.Now,
                    Description="Mouse Razer", Price=150,
                    Url="razer-mouse", IsHome=true, MainImage="razer-mouse.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="28", Name="Klavye Razer", CreationDate=DateTime.Now,
                    Description="Klavye Razer", Price=685, Discount=10,
                    Url="razer-klavye", IsHome=true, MainImage="razer-klavye.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="29", Name="steelseries-kulaklık", CreationDate=DateTime.Now,
                    Description="steelseries-kulaklık", Price=975, Discount=5,
                    Url="steelseries-kulaklik", IsHome=true, MainImage="steelseries-kulaklik.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="30", Name="air-pods", CreationDate=DateTime.Now,
                    Description="air-pods", Price=4000, Discount=5,
                    Url="air-pods", IsHome=true, MainImage="air-pods.jfif",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="31", Name="Playstation 5", CreationDate=DateTime.Now,
                    Description="Playstation 5", Price=12000, Discount=7,
                    Url="playstation5", IsHome=true, MainImage="playstation5.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },
                new Product(){Id="32", Name="Playstation 4", CreationDate=DateTime.Now,
                    Description="Playstation 4", Price=6000, Discount=20,
                    Url="playstation4", IsHome=true, MainImage="playstation4.jpg",
                    ShortDescription="lorem ipsum dat color...", IsActive=true,
                },

            };
            builder.HasData(products);
        }
    }
}